-- AlterTable
ALTER TABLE "User" ADD COLUMN     "autoExecMin" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "escalation1Min" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "escalation2Min" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "escalation3Min" INTEGER NOT NULL DEFAULT 10;
