import path from 'path';
import http from 'http';
import dotenv from 'dotenv';
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });
dotenv.config();

const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:3001';

async function executePendingTx(txId: string): Promise<{ success: boolean; txHash?: string; amount?: string; toAddress?: string; network?: string; error?: string }> {
  const BOT_SHARED_SECRET = process.env.BOT_SHARED_SECRET;
  if (!BOT_SHARED_SECRET) return { success: false, error: 'BOT_SHARED_SECRET not configured' };
  try {
    const res = await fetch(`${BACKEND_URL}/api/agent/pending-tx/${txId}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Bot-Secret': BOT_SHARED_SECRET },
    });
    const data = await res.json() as any;
    if (!res.ok) return { success: false, error: data.error || 'Execution failed' };
    return { success: true, txHash: data.txHash, amount: data.amount, toAddress: data.toAddress, network: data.network };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : 'Unknown error' };
  }
}

async function rejectPendingTx(txId: string): Promise<{ success: boolean; error?: string }> {
  const BOT_SHARED_SECRET = process.env.BOT_SHARED_SECRET;
  if (!BOT_SHARED_SECRET) return { success: false, error: 'BOT_SHARED_SECRET not configured' };
  try {
    const res = await fetch(`${BACKEND_URL}/api/agent/pending-tx/${txId}/reject`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Bot-Secret': BOT_SHARED_SECRET },
    });
    const data = await res.json() as any;
    if (!res.ok) return { success: false, error: data.error || 'Rejection failed' };
    return { success: true };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : 'Unknown error' };
  }
}

async function executeSwapForAlert(alertId: string): Promise<{ success: boolean; fromAmount?: string; toAmount?: string; txHash?: string; network?: string; error?: string }> {
  // Two-factor authentication to backend:
  //   (1) BOT_SHARED_SECRET in X-Bot-Secret, proves call originates from this bot process.
  //   (2) per-alert BotSwapGrant looked up by alertId on the backend, generated by the
  //       worker at alert-create time, expires in 30 min, single-use.
  // Replaces the prior model which reused a 7-day web JWT for any user.
  try {
    const BOT_SHARED_SECRET = process.env.BOT_SHARED_SECRET;
    if (!BOT_SHARED_SECRET) {
      return { success: false, error: 'BOT_SHARED_SECRET not configured' };
    }
    const res = await fetch(`${BACKEND_URL}/api/bot-swap/execute`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Bot-Secret': BOT_SHARED_SECRET,
      },
      body: JSON.stringify({ alertId }),
    });
    const data = await res.json() as any;
    if (!res.ok) return { success: false, error: data.error || 'Swap failed' };
    return { success: true, fromAmount: data.fromAmount, toAmount: data.toAmount, txHash: data.txHash, network: data.network };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : 'Unknown error' };
  }
}

import { Telegraf, Markup, Context } from 'telegraf';
import { PrismaClient } from '@prisma/client';
import { Worker } from 'bullmq';
import Redis from 'ioredis';
import { getAiInsight } from './ai-insight';

if (!process.env.TELEGRAM_BOT_TOKEN) {
  console.error('TELEGRAM_BOT_TOKEN is required');
  process.exit(1);
}

const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);
const prisma = new PrismaClient();
const redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379', {
  maxRetriesPerRequest: null,
});

// --- Commands ---

bot.start(async (ctx: Context) => {
  const chatId = ctx.chat!.id.toString();
  const firstName = ctx.from?.first_name || 'there';

  await ctx.reply(
    `🛡️ *Welcome to GuardAgent, ${firstName}!*\n\n` +
    `I monitor stablecoin prices 24/7 on Arc and send instant alerts.\n\n` +
    `📲 *Your Telegram Chat ID:*\n\`${chatId}\`\n\n` +
    `Copy this ID and paste it in the GuardAgent app to link your wallet.\n\n` +
    `*Commands:*\n` +
    `/link <code>. Link your wallet using a code from the app\n` +
    `/status. Check your monitoring status\n` +
    `/rules. List your active rules\n` +
    `/pause. Pause all alerts\n` +
    `/resume. Resume all alerts\n` +
    `/help. Show help`,
    { parse_mode: 'Markdown' }
  );
});

bot.command('link', async (ctx: Context) => {
  const chatId = ctx.chat!.id.toString();
  const args = (ctx.message as { text: string }).text.split(' ').slice(1);
  const code = args[0]?.trim();

  if (!code) {
    await ctx.reply('❌ Usage: `/link <code>`\n\nGet your link code from the GuardAgent app.', { parse_mode: 'Markdown' });
    return;
  }

  try {
    const walletAddress = await redis.get(`link:${code}`);
    if (!walletAddress) {
      await ctx.reply('❌ Invalid or expired code. Please generate a new one from the app.');
      return;
    }

    // Block silent takeover: if this wallet is already linked to a different chatId,
    // require the user to explicitly /unlink from the existing chat first.
    const existing = await prisma.user.findUnique({
      where: { walletAddress },
      select: { telegramChatId: true },
    });
    if (existing?.telegramChatId && existing.telegramChatId !== chatId) {
      await ctx.reply(
        '❌ This wallet is already linked to a different Telegram account.\n' +
        'Run /unlink from the existing Telegram account first, or regenerate a link code in the app.'
      );
      return;
    }

    await prisma.user.update({
      where: { walletAddress },
      data: { telegramChatId: chatId, telegramLinked: true },
    });
    await redis.del(`link:${code}`);

    await ctx.reply(
      `✅ *Wallet linked successfully!*\n\n` +
      `Wallet: \`${walletAddress.slice(0, 6)}...${walletAddress.slice(-4)}\`\n\n` +
      `You'll now receive instant price alerts here. Use /rules to see your monitoring rules.`,
      { parse_mode: 'Markdown' }
    );
  } catch (err) {
    console.error('Link error:', err);
    await ctx.reply('❌ Something went wrong. Please try again.');
  }
});

bot.command('status', async (ctx: Context) => {
  const chatId = ctx.chat!.id.toString();
  const user = await prisma.user.findFirst({
    where: { telegramChatId: chatId },
    include: {
      rules: { where: { isActive: true } },
      _count: { select: { alerts: true } },
    },
  });

  if (!user) {
    await ctx.reply('❌ Wallet not linked. Use `/link <code>` from the app.', { parse_mode: 'Markdown' });
    return;
  }

  const paused = !user.isActive;
  await ctx.reply(
    `${paused ? '⏸️' : '✅'} *GuardAgent Status*\n\n` +
    `👛 Wallet: \`${user.walletAddress.slice(0, 6)}...${user.walletAddress.slice(-4)}\`\n` +
    `📋 Active rules: ${user.rules.length}\n` +
    `🔔 Total alerts: ${user._count.alerts}\n` +
    `💎 Plan: ${user.plan}\n` +
    `📡 Monitoring: ${paused ? '*PAUSED*' : '*ACTIVE*'}`,
    { parse_mode: 'Markdown' }
  );
});

bot.command('rules', async (ctx: Context) => {
  const chatId = ctx.chat!.id.toString();
  const user = await prisma.user.findFirst({
    where: { telegramChatId: chatId },
    include: { rules: { where: { isActive: true } } },
  });

  if (!user) {
    await ctx.reply('❌ Wallet not linked. Use `/link <code>` from the app.', { parse_mode: 'Markdown' });
    return;
  }
  if (user.rules.length === 0) {
    await ctx.reply('📋 No active rules. Create some in the GuardAgent app!');
    return;
  }

  const list = user.rules.map((r: { name: string; tokenSymbol: string; condition: string; threshold: number }, i: number) => {
    const cond = r.condition === 'ABOVE' ? '▲' : '▼';
    return `${i + 1}. *${r.name}*\n   ${r.tokenSymbol} ${cond} $${r.threshold.toLocaleString()}`;
  }).join('\n\n');

  await ctx.reply(`📋 *Your Active Rules:*\n\n${list}`, { parse_mode: 'Markdown' });
});

bot.command('pause', async (ctx: Context) => {
  const chatId = ctx.chat!.id.toString();
  const updated = await prisma.user.updateMany({
    where: { telegramChatId: chatId },
    data: { isActive: false },
  });
  if (updated.count > 0) {
    await ctx.reply('⏸️ Monitoring paused. Use /resume to re-enable alerts.');
  } else {
    await ctx.reply('❌ No wallet linked. Use `/link <code>` first.', { parse_mode: 'Markdown' });
  }
});

bot.command('resume', async (ctx: Context) => {
  const chatId = ctx.chat!.id.toString();
  const updated = await prisma.user.updateMany({
    where: { telegramChatId: chatId },
    data: { isActive: true },
  });
  if (updated.count > 0) {
    await ctx.reply('▶️ Monitoring resumed! You will receive alerts again.');
  } else {
    await ctx.reply('❌ No wallet linked. Use `/link <code>` first.', { parse_mode: 'Markdown' });
  }
});

bot.command('unlink', async (ctx: Context) => {
  const chatId = ctx.chat!.id.toString();
  // Revoke all web sessions for the owning user too, otherwise a long-lived JWT
  // can still be used by any code that picks the latest session for this user.
  const user = await prisma.user.findFirst({ where: { telegramChatId: chatId }, select: { id: true } });
  const updated = await prisma.user.updateMany({
    where: { telegramChatId: chatId },
    data: { telegramChatId: null, telegramLinked: false },
  });
  if (user) {
    await prisma.session.deleteMany({ where: { userId: user.id } });
  }
  if (updated.count > 0) {
    await ctx.reply('✅ Telegram unlinked and all web sessions revoked. Re-login in the app if you want to continue.');
  } else {
    await ctx.reply('❌ No wallet was linked to this account.');
  }
});

bot.command('help', async (ctx: Context) => {
  await ctx.reply(
    '🛡️ *GuardAgent Help*\n\n' +
    '/start. Welcome & your Chat ID\n' +
    '/link <code>. Link wallet using app code\n' +
    '/status. Your monitoring status\n' +
    '/rules. List active rules\n' +
    '/pause. Pause all alerts\n' +
    '/resume. Resume alerts\n' +
    '/unlink. Unlink your wallet\n' +
    '/help. Show this message\n\n' +
    '⚡ *Escalation:* T+2, T+5 min reminders → T+10 min voice message 🎙️\n' +
    '💡 Manage rules at the GuardAgent web app.',
    { parse_mode: 'Markdown' }
  );
});

// --- Approve pending transfer (Guardian approval flow) ---
bot.action(/^approve_tx:(.+)$/, async (ctx) => {
  const txId = ctx.match[1];
  try {
    const tx = await prisma.agentTransaction.findUnique({ where: { id: txId }, select: { userId: true, status: true, amount: true, tokenIn: true, toAddress: true } });
    if (!tx) { await ctx.answerCbQuery('Transaction not found'); return; }
    if (tx.status !== 'PENDING_APPROVAL') { await ctx.answerCbQuery('Already processed'); return; }
    const owner = await prisma.user.findUnique({ where: { id: tx.userId }, select: { telegramChatId: true } });
    const pressedBy = ctx.chat?.id?.toString();
    if (!owner?.telegramChatId || !pressedBy || owner.telegramChatId !== pressedBy) {
      await ctx.answerCbQuery('Not authorized');
      return;
    }
    await ctx.answerCbQuery('⏳ Executing...');
    await ctx.editMessageReplyMarkup(undefined);
    await ctx.reply(`⏳ <b>Executing transfer...</b>\n\nSending <b>${tx.amount} ${tx.tokenIn}</b>...`, { parse_mode: 'HTML' });
    const result = await executePendingTx(txId);
    if (result.success) {
      const explorerBase = 'https://testnet.arcscan.app';
      const toShort = result.toAddress ? `${result.toAddress.slice(0, 6)}...${result.toAddress.slice(-4)}` : '';
      await ctx.reply(
        `✅ <b>Transfer complete!</b>\n\n` +
        `📤 Sent: <b>${result.amount}</b>\n` +
        `📍 To: <code>${toShort}</code>\n` +
        (result.txHash ? `🔗 <a href="${explorerBase}/tx/${result.txHash}">View on Arcscan</a>` : ''),
        { parse_mode: 'HTML' }
      );
    } else {
      await ctx.reply(`❌ Transfer failed: ${result.error}`, { parse_mode: 'HTML' });
    }
  } catch (err) {
    console.warn('[bot] approve_tx handler failed for tx', txId, err);
    await ctx.answerCbQuery('Error');
  }
});

// --- Reject pending transfer ---
bot.action(/^reject_tx:(.+)$/, async (ctx) => {
  const txId = ctx.match[1];
  try {
    const tx = await prisma.agentTransaction.findUnique({ where: { id: txId }, select: { userId: true, status: true } });
    if (!tx) { await ctx.answerCbQuery('Transaction not found'); return; }
    if (tx.status !== 'PENDING_APPROVAL') { await ctx.answerCbQuery('Already processed'); return; }
    const owner = await prisma.user.findUnique({ where: { id: tx.userId }, select: { telegramChatId: true } });
    const pressedBy = ctx.chat?.id?.toString();
    if (!owner?.telegramChatId || !pressedBy || owner.telegramChatId !== pressedBy) {
      await ctx.answerCbQuery('Not authorized');
      return;
    }
    await ctx.answerCbQuery('❌ Rejected');
    await ctx.editMessageReplyMarkup(undefined);
    await rejectPendingTx(txId);
    await ctx.reply('❌ Transfer rejected and cancelled.');
  } catch (err) {
    console.warn('[bot] reject_tx handler failed for tx', txId, err);
    await ctx.answerCbQuery('Error');
  }
});

// --- Auto-execute handler (manual button press) ---
bot.action(/^auto_exec:(.+)$/, async (ctx) => {
  const alertId = ctx.match[1];
  try {
    const alert = await prisma.alert.findUnique({ where: { id: alertId }, select: { userId: true, status: true } });
    if (!alert || alert.status === 'ACKNOWLEDGED') {
      await ctx.answerCbQuery('Already processed');
      return;
    }
    // Ownership check, prevent IDOR via crafted callback_data from another user's client.
    const owner = await prisma.user.findUnique({ where: { id: alert.userId }, select: { telegramChatId: true } });
    const pressedBy = ctx.chat?.id?.toString();
    if (!owner?.telegramChatId || !pressedBy || owner.telegramChatId !== pressedBy) {
      await ctx.answerCbQuery('Not authorized');
      return;
    }
    await ctx.answerCbQuery('⚡ Executing...');
    await ctx.editMessageReplyMarkup(undefined);
    await ctx.reply(`⚡ <b>Executing protective swap...</b>\n🤖 Agent is processing...`, { parse_mode: 'HTML' });

    const swapResult = await executeSwapForAlert(alertId);

    await prisma.alert.update({
      where: { id: alertId },
      data: { status: 'ACKNOWLEDGED', executedAt: new Date() },
    });

    if (swapResult.success) {
      const explorerBase = 'https://testnet.arcscan.app';
      await ctx.reply(
        `✅ <b>Swap executed!</b>\n\n` +
        `📤 Sold: <b>${swapResult.fromAmount}</b>\n` +
        `📥 Received: <b>${swapResult.toAmount}</b>\n` +
        `🌐 Network: Arc Testnet\n` +
        `🔗 <a href="${explorerBase}/tx/${swapResult.txHash}">View on Arcscan</a>`,
        { parse_mode: 'HTML' }
      );
    } else {
      await ctx.reply(`⚠️ Swap failed: ${swapResult.error}`, { parse_mode: 'HTML' });
    }
  } catch (err) {
    console.warn('[bot] auto_exec handler failed for alert', alertId, err);
    await ctx.answerCbQuery('Error');
  }
});

// --- Inline button callbacks ---

// Acknowledge alert
bot.action(/^ack:(.+)$/, async (ctx) => {
  const alertId = ctx.match[1];
  try {
    const alert = await prisma.alert.findUnique({ where: { id: alertId }, select: { userId: true } });
    if (!alert) { await ctx.answerCbQuery('Already processed'); return; }
    const owner = await prisma.user.findUnique({ where: { id: alert.userId }, select: { telegramChatId: true } });
    const pressedBy = ctx.chat?.id?.toString();
    if (!owner?.telegramChatId || !pressedBy || owner.telegramChatId !== pressedBy) {
      await ctx.answerCbQuery('Not authorized');
      return;
    }
    await prisma.alert.update({ where: { id: alertId }, data: { status: 'ACKNOWLEDGED' } });
    await ctx.answerCbQuery('✅ Alert acknowledged');
    await ctx.editMessageReplyMarkup(undefined);
    await ctx.reply('✅ Alert acknowledged. Monitoring continues.');
  } catch (err) {
    console.warn('[bot] ack handler failed for alert', alertId, err);
    await ctx.answerCbQuery('Already processed');
  }
});

// Disable rule
bot.action(/^disable_rule:(.+)$/, async (ctx) => {
  const ruleId = ctx.match[1];
  try {
    const rule = await prisma.rule.findUnique({ where: { id: ruleId }, select: { userId: true } });
    if (!rule) { await ctx.answerCbQuery('Not found'); return; }
    const owner = await prisma.user.findUnique({ where: { id: rule.userId }, select: { telegramChatId: true } });
    const pressedBy = ctx.chat?.id?.toString();
    if (!owner?.telegramChatId || !pressedBy || owner.telegramChatId !== pressedBy) {
      await ctx.answerCbQuery('Not authorized');
      return;
    }
    await prisma.rule.update({ where: { id: ruleId }, data: { isActive: false } });
    await ctx.answerCbQuery('🔕 Rule disabled');
    await ctx.editMessageReplyMarkup(undefined);
    await ctx.reply('🔕 Rule disabled. Re-enable it anytime in the GuardAgent app.');
  } catch (err) {
    console.warn('[bot] disable_rule handler failed for rule', ruleId, err);
    await ctx.answerCbQuery('Error');
  }
});

// --- BullMQ Alert delivery worker ---

const alertWorker = new Worker(
  'alerts',
  async (job) => {
    // Regular text alert with inline buttons
    if (job.name === 'send-alert') {
      const { alertId, chatId, message, ruleId, tokenSymbol, condition, threshold, currentPrice, userId } = job.data as {
        alertId: string;
        chatId: string;
        message: string;
        ruleId?: string;
        tokenSymbol?: string;
        condition?: string;
        threshold?: number;
        currentPrice?: number;
        userId?: string;
      };

      try {
        // Append AI insight if price data is available
        let finalMessage = message;
        if (tokenSymbol && condition && threshold && currentPrice) {
          const insight = await getAiInsight(tokenSymbol, condition, threshold, currentPrice);
          if (insight) {
            finalMessage += `\n\n🤖 <i>${insight}</i>`;
          }
        }

        // Check if user has agent wallet → show Execute button immediately
        const hasAgentWallet = userId
          ? await prisma.agentWallet.findUnique({ where: { userId }, select: { id: true } }).then(w => !!w)
          : false;

        const keyboard = ruleId
          ? Markup.inlineKeyboard([
              ...(hasAgentWallet ? [Markup.button.callback('⚡ Execute', `auto_exec:${alertId}`)] : []),
              Markup.button.callback('✅ Acknowledge', `ack:${alertId}`),
              Markup.button.callback('🔕 Disable Rule', `disable_rule:${ruleId}`),
            ])
          : undefined;

        await bot.telegram.sendMessage(chatId, finalMessage, {
          parse_mode: 'HTML',
          ...keyboard,
        });

        // Update status (ignore if alertId doesn't exist, e.g. test jobs)
        await prisma.alert.update({
          where: { id: alertId },
          data: { status: 'SENT', sentAt: new Date() },
        }).catch((err) => { console.warn('[bot] alert status update failed for', alertId, err); });

        console.log(`Alert ${alertId} sent to ${chatId}`);
      } catch (err) {
        console.error(`Failed to send alert ${alertId}:`, err);
      }
    }

    // Auto-execute job at T+15 (if autoMode ON)
    if (job.name === 'auto-execute') {
      const { alertId, chatId, tokenSymbol, condition, threshold, currentPrice, userId } = job.data as {
        alertId: string; chatId: string; tokenSymbol: string;
        condition: string; threshold: number; currentPrice: number; userId?: string;
      };

      try {
        const conditionLabel = condition === 'ABOVE' ? 'above' : 'below';

        await bot.telegram.sendMessage(
          chatId,
          `⚡ <b>AutoMode: Executing protective swap...</b>\n\n` +
          `<b>${tokenSymbol}</b> ${conditionLabel} $${threshold.toLocaleString()} · Current: <b>$${currentPrice.toLocaleString()}</b>\n` +
          `🤖 Agent is processing...`,
          { parse_mode: 'HTML' }
        );

        // Auto-execute uses the same per-alert grant, no userId-only path.
        let swapResult = { success: false, fromAmount: '', toAmount: '', txHash: '', error: 'No alertId' };
        if (alertId) swapResult = await executeSwapForAlert(alertId) as any;

        await prisma.alert.update({
          where: { id: alertId },
          data: { executedAt: new Date(), status: 'ACKNOWLEDGED' },
        }).catch((err) => { console.warn('[bot] auto-execute alert update failed for', alertId, err); });

        if (swapResult.success) {
          const explorerBase = 'https://testnet.arcscan.app';
          await bot.telegram.sendMessage(
            chatId,
            `✅ <b>Protective swap complete!</b>\n\n` +
            `📤 Sold: <b>${swapResult.fromAmount}</b>\n` +
            `📥 Received: <b>${swapResult.toAmount}</b>\n` +
            `🌐 Network: Arc Testnet\n` +
            `🔗 <a href="${explorerBase}/tx/${swapResult.txHash}">View on Arcscan</a>`,
            { parse_mode: 'HTML' }
          );
        } else {
          await bot.telegram.sendMessage(chatId, `⚠️ AutoMode swap failed: ${swapResult.error}`, { parse_mode: 'HTML' });
        }

        console.log(`Auto-executed alert ${alertId}: ${swapResult.success ? 'OK' : swapResult.error}`);
      } catch (err) {
        console.error(`Auto-execute failed for ${alertId}:`, err);
      }
    }
  },
  { connection: redis }
);

alertWorker.on('failed', (job, err) => {
  console.error(`Alert job ${job?.id} failed:`, err);
});

// --- Start ---
let botReady = false;

bot.launch().catch((e) => {
  console.error('Bot launch failed (Telegram unreachable or invalid TELEGRAM_BOT_TOKEN):', e instanceof Error ? e.message : e);
  console.error('The process stays up so the health endpoint and the alert queue worker keep running. Set a valid TELEGRAM_BOT_TOKEN from @BotFather and restart the bot to enable Telegram delivery.');
});
console.log('GuardAgent Telegram Bot starting (polling)...');

setTimeout(async () => {
  try {
    const me = await bot.telegram.getMe();
    botReady = true;
    console.log(`✅ Bot @${me.username} is running and connected to Telegram`);
  } catch (e) {
    console.error('❌ Bot connection error:', e);
  }
}, 2000);

const HEALTH_PORT = parseInt(process.env.BOT_HEALTH_PORT || '3002', 10);
http
  .createServer((req, res) => {
    if (req.url !== '/health') {
      res.writeHead(404).end();
      return;
    }
    const redisOk = redis.status === 'ready';
    const ok = botReady && redisOk;
    res.writeHead(ok ? 200 : 503, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok, botReady, redis: redis.status }));
  })
  .listen(HEALTH_PORT, '0.0.0.0', () => {
    console.log(`Health endpoint listening on :${HEALTH_PORT}/health`);
  });

process.once('SIGINT', () => { bot.stop('SIGINT'); redis.quit(); });
process.once('SIGTERM', () => { bot.stop('SIGTERM'); redis.quit(); });
